apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
  namespace: flux

spec:
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: mohansai1997/gitops-poc
          ports:
            - containerPort: 8000

