apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-yaml-file
  namespace: flux
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus_master'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'new_job'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']