apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
  namespace: argocd
  annotations:
    fluxcd.io/automated: "true"
spec:
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: mohansai1997/gitops-poc:22
          env:
          - name: NAME
            value: "Version=22"
          ports:
            - containerPort: 8000
