apiVersion: v1
kind: Service
metadata:
  name: flask-service 
  namespace: argocd
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32500

