apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: gitops-poc-17506377-test
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 33000